name: Front-end CI

on: push

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v2

      - name: Build frontend image
        run: docker build -t frontend .

      - name: Check stylesheet with eslint
        run: docker run frontend yarn eslint --ext .js,.vue

      - name: Run back-end tests
        run: |
          docker run\
            --volume ${PWD}:/client\
            frontend bash -c "yarn && yarn test:ci:unit:coverage"

      - name: Publish tests to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./client/coverage/coverage-final.json
          flags: unittests
          fail_ci_if_error: true
          verbose: false
