name: Front-end CI

on: push

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v2

      - name: Build frontend image
        run: docker build -t frontend .

      - name: Check eslint standards
        run: docker run frontend yarn eslint --ext .js,.vue

      - name: Display folders
        run: ls

      - name: Test front-end
        run: |
          docker run\
            --volume ${PWD}:/client\
            frontend bash -c "yarn test:ci:unit:coverage"

      - name: Publish code coverage
        uses: codecov/codecov-action@v1
        with:
          files: ./client/coverage/coverage-final.json
          flags: unittests # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: false # optional (default = false)
